### ISSUE TITLE
CloudCompare UI is frozen while running a Python script

### ISSUE THREAD

**Issue by AccessArctic** [tmontaigu/CloudCompare-PythonPlugin#28]
I have noticed that while running a Python script via the embedded version of CCPP, the UI is completely inaccessible until the script end's.

Both this codes (with or without threading) get the same result : the CC UI is frozen until the code finish

```
import time

for x in range(100):
    print(x)
    time.sleep(0.1) 
```
or 

```
import time
import threading

class ThreadTest (threading.Thread):
    def __init__(self, ID):     
        self.threadID = ID
        threading.Thread.__init__(self)   # (call the thread constructor)

    def run(self):
        for x in range(100):
            print(x)
            time.sleep(0.1)   

Tx = ThreadTest(1)      
Tx.start()                  # start thread,
Tx.join()                  # wait for the thread to finish executing
```
Is that an expected behaviour ? Could it be avoided (for example when trying to run a script that will regularly read a stream of points and add them to a point_cloud in the UI, yet allowing the user to interact with the UI in the meantime.

**Comment by tmontaigu** [comment]
(Transcripting the email response as it may be useful to others)

This is expected, the same thing would happen in C++ plugins.
When the python code is executed it runs in the main thread, and the main thread (at least in Qt) is responsible for updating the UI and responding to events. So if your code is doing heavy computation the main thread won't spend time updating the UI so it will appear as frozen.

The solution is generally to send the computation in another Thread so that the main thread can keep the UI responsive. However in your example you use `join` on the thread you created, which will make the main thread block until the other thread is done, so no update of the UI is done, we have the same problem.

At the moment the only solution for python scripts is to use the `pycc.ProcessEvents()` and `pycc.RunInThread` functions which allows to keep the UI reponsive while some heavy computation is done.


```Python
import time
  
import threading
import pycc
  
class ThreadTest(threading.Thread):
    def __init__(self, ID):
        self.threadID = ID
        threading.Thread.__init__(self)
  
    def run(self):
        for x in range(100):
            print(x)
            time.sleep(0.1)   
  
Tx = ThreadTest(10)
Tx.start() 
while Tx.is_alive():
    pycc.ProcessEvents()
Tx.join()
```
 
```Python
import time
import pycc
  
for x in range(100):
    print(x)
    time.sleep(0.1)
    pycc.ProcessEvents()
  
def fn():
    for x in range(100):
        print(x)
        time.sleep(0.1)
  
pycc.RunInThread(fn)
```
Qt normally offers more ways to handle these types of problems.
However, multi-threading and the aspects of the interactions between Python threads and C++ threads as well as Qt C++ and Qt Python  are not yet fixed in the Plugin so other problem will come out. 

These are rather though problems which haven't yet been though out and explored in the plugin yet.
