### ISSUE TITLE
Python (from CCPP) execute old version of .py imported code

### ISSUE THREAD

**Issue by AccessArctic** [tmontaigu/CloudCompare-PythonPlugin#29]
Hello,

When using the plugin Python editor, it seems that when running a script Python use some cache version of the imported class/def even them having been saved or closed from the editor.

Removing the cache folder from the where these class are stored it ; closing the python editor (directly or via the "close and return to CC" command doesn't reload the last version of the code.

Only stopping CC altogether seems to allow the code to reload the last version.

Thanks

**Comment by tmontaigu** [comment]
Hello,

This is normal, The plugins starts up a Python interpreter and keeps it alive until CloudCompare closes.
When you `import` modules the interpreter uses a cache to and does not reimport something that has already been imported once even if the code of the module changed.

So when you run a script multiple times in the embedded plugin, since the interpreter was not restarted each time, it won't reload your new version of the module. 

And as their is currently no way to restart the embeded interpreter the solution is either to restart cloudcompare or use [importlib.reload](https://docs.python.org/3/library/importlib.html#importlib.reload)

```Python
import importlib
import mymodule

# force the reload
importlib.reload(mymodule)
```

**Comment by AccessArctic** [comment]
Thanks,
I will have a look at it.
