### ISSUE TITLE
Add M3C2 change detection algorithm to the repo

### ISSUE THREAD

**Issue by fredpeertje** [tmontaigu/CloudCompare-PythonPlugin#34]
Hi Thomas,

Is it possible for you to add M3C2 to the repo so it can be used in python? This is a change detection algorithm in CloudCompare: [https://github.com/CloudCompare/CloudCompare/tree/master/plugins/core/Standard/qM3C2](https://github.com/CloudCompare/CloudCompare/tree/master/plugins/core/Standard/qM3C2 ).

**Comment by tmontaigu** [comment]
This is tricky because the M3C2 thing is a plugin, and this project works both as a plugin and a standalone python package.

The thing is, CloudCompare has no mechanism that allows plugin to use other plugin`s functionnalities so we cant just make a wrapper that call the plugin. So we would have to do our own thing
