### ISSUE TITLE
Cannot Import Installed Package (open3d) from REPL

### ISSUE THREAD

**Issue by ludennis** [tmontaigu/CloudCompare-PythonPlugin#44]
OS: Windows
CC version: 2.12.2
Installed PythonPlugin through the windows installer

My goal is to ultimately convert cc point cloud into open3d's point cloud and use some of their functionalities, then convert the point cloud back to cc point cloud. On my way of achieving this, I have encountered a problem where I couldn't import `open3d` after installing the package through the pip package manager GUI.

I installed open3d with the plugin's pip package manager and have it shown in the list of installed packages:

![unnamed](https://user-images.githubusercontent.com/3859423/209474285-f763ed72-75c6-4e89-826c-d6b3a8136439.png)

But when I import it in the interactive REPL, it showed that there's no module named 'open3d'. And with some checking with `pkg_resources`, it didn't list `open3d` as an installed package either:

![unnamed](https://user-images.githubusercontent.com/3859423/209474333-367e0dbc-fd45-4afa-93b2-e2957ba54ee4.png)

Wondering if there's some steps I have missed to make it work, or that cloud compare python plugin does not support `open3d`.

**Comment by tmontaigu** [comment]
That is weird, I am able to import open3d in the REPL

![image](https://user-images.githubusercontent.com/15125341/209481099-7bd92612-a0d5-4241-a6eb-cc1c62e38681.png)

I installed it via the pip GUI of the plugin.

One thing to note, is that since your CloudCompare is likely installed in `C:\Program\CloudCompare`,
thus the env of the plugin is located somewhere inside this directory tree, and you generally need admin access to be able to 
modify anything that is located in `C:\Program`.

So to be able to install something you need to start CloudCompare as an administrator, then you should be able to install open3d (it may take some time and freeze the ui a bit but it should work)

**Comment by ludennis** [comment]
Thanks for your prompt reply! And yes, my CloudCompare was installed in the location `C:\Program Files\CloudCompare`

Was able to get it to import `open3d` with the following steps:
1. Run CloudCompare as an administrator
2. Uninstall `open3d` via the pip GUI of the plugin
3. Install `open3d` with "Upgrade" and "Force" checked
4. Add `C:\Program Files\CloudCompare\plugins\Python\Scripts` to `PATH` environment variable
![unnamed](https://user-images.githubusercontent.com/3859423/209519415-e6693747-b47f-4b6b-aa11-538a8791ff3e.png)

Thanks for helping me! Will close it now.
